apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: pnw-social
  name: mastodon
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: moria.ob1.ninja
    path: "/mnt/herald/bham-social/mastodon"