kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: pnw-social
  name: redis-backup
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi # There must be 100MB available in the pool of 1GB to get scheduled
